# Generated by Django 2.1a1 on 2018-06-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_auto_20180615_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='name',
            field=models.CharField(help_text='Name', max_length=200),
        ),
    ]
