# Generated by Django 2.1a1 on 2018-06-15 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0003_auto_20180615_0902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lot',
            options={'ordering': ['name'], 'verbose_name': 'Лот', 'verbose_name_plural': 'Лоты'},
        ),
    ]
