# Generated by Django 2.1a1 on 2018-06-15 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0007_auto_20180615_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2018, 6, 15, 10, 33, 15, 599184)),
        ),
        migrations.AlterField(
            model_name='lot',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2018, 6, 15, 10, 33, 15, 599152)),
        ),
    ]
