# Generated by Django 2.1a1 on 2018-06-15 10:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rate', '0008_auto_20180615_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinnerLot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Победитель лота',
                'verbose_name_plural': 'Победители аукциона',
                'ordering': ['user'],
            },
        ),
        migrations.AlterField(
            model_name='lot',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2018, 6, 15, 10, 43, 58, 456109)),
        ),
        migrations.AlterField(
            model_name='lot',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2018, 6, 15, 10, 43, 58, 456073)),
        ),
        migrations.AddField(
            model_name='winnerlot',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.Lot'),
        ),
        migrations.AddField(
            model_name='winnerlot',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.Rate'),
        ),
        migrations.AddField(
            model_name='winnerlot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
