# Generated by Django 2.1a1 on 2018-06-15 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0009_auto_20180615_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='winnerlot',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 6, 15, 10, 51, 35, 939149)),
        ),
        migrations.AlterField(
            model_name='lot',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2018, 6, 15, 10, 51, 35, 938021)),
        ),
        migrations.AlterField(
            model_name='lot',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2018, 6, 15, 10, 51, 35, 937988)),
        ),
    ]
