# Generated by Django 2.1a1 on 2018-06-15 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0010_auto_20180615_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2018, 6, 15, 10, 52, 35, 451741)),
        ),
        migrations.AlterField(
            model_name='lot',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2018, 6, 15, 10, 52, 35, 451697)),
        ),
        migrations.AlterField(
            model_name='winnerlot',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 6, 15, 10, 52, 35, 452869)),
        ),
    ]
