# Generated by Django 2.1a1 on 2018-06-15 10:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0012_auto_20180615_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2018, 6, 15, 10, 56, 34, 224012)),
        ),
        migrations.AlterField(
            model_name='lot',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2018, 6, 15, 10, 56, 34, 223977)),
        ),
        migrations.AlterField(
            model_name='winnerlot',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 6, 15, 10, 56, 34, 225089, tzinfo=utc)),
        ),
    ]
