# Generated by Django 2.1a1 on 2018-06-15 10:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0013_auto_20180615_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2018, 6, 15, 10, 58, 8, 951045, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lot',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2018, 6, 15, 10, 58, 8, 951016, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='winnerlot',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 6, 15, 10, 58, 8, 952312, tzinfo=utc)),
        ),
    ]
