# Generated by Django 2.1a1 on 2018-06-15 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0015_auto_20180615_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winnerlot',
            name='lot',
        ),
    ]
