# Generated by Django 2.1a1 on 2018-06-22 10:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0017_auto_20180615_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='date_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='lot',
            name='date_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='winnerlot',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
