# Generated by Django 2.1a1 on 2018-06-22 10:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0018_auto_20180622_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
